{
 "title": "Demo Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_milliseconds_count{uri=\"/\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 9, "y": 15 },
   "targets": [
    {
     "expr": "system_cpu_usage{label1=\"value1\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}