global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      # Collect metrics from the OTel Collector's Prometheus endpoint.
      # hostname matches line 2 of compose file
      # Port matches line 12 of compose file
      - targets: ['otel-collector:8889']

