global:
  scrape_interval: 15s
  evaluation_interval: 15s

#scrape_configs:
#  - job_name: 'otel-collector'
#    static_configs:
#      - targets: ['otel-collector:8889']  # Collect metrics from the OTel Collector's Prometheus endpoint

scrape_configs:
  - job_name: 'test-app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"] # this app address
